#!/bin/bash
# SageMaker invokes the container as: docker run <image> serve
# This script is that entrypoint.
exec uvicorn app:app \
    --host 0.0.0.0 \
    --port 8080 \
    --workers 1 \
    --timeout-keep-alive 75
